### ISSUE TITLE
Strava 0 Watt Challenge

### ISSUE THREAD

**Issue by bvanelli** [strautomator/core#13]
Hello,

Recently I've been wondering to implement a a feature to track what is the longest you rode with your bike without doing any effort (hence, 0W challenge). I wanted to implement as a challenge that is tracked throughout your activities and updates whenever you had a new personal best, that's why I came across your project.

The concept is simple: if you have data from either power meter or cadence sensor, it would track the individual distance segments that you covered without doing any effort, and it would take the max segment for the ride. It would then be a select-able metric for your strava automation.

My questions are:

- Do you think this is doable using the strava api?
- Would you be willing to review such feature?
- Could you point me out, in the current implementation where this could be done?

I'm of course willing to implement this feature.

**Comment by igoramadas** [comment]
Hi Brunno,

technically this is possible to do, but in practice I wouldn't trust the data so much as Strava does a lot of post-processing to remove data points that they consider "redundant". Even Garmin (when recording in Smart mode) will do that. So the distance of a 0-effort segment could be off by a few hundred meters, maybe more.

If implemented in Strautomator, this would be part of the "Personal records" feature (main method [here](https://github.com/strautomator/core/blob/master/src/strava/athletes.ts#L111) and interface schema [here](https://github.com/strautomator/core/blob/master/src/strava/types.ts#L339)). And the data would come from the activity stream [APIs](https://developers.strava.com/docs/reference/#api-Streams-getActivityStreams).

I currently don't fetch streams for activity processing, so such feature would effectively double the amount of API calls per activity processed. Strava is known to be very very restrictive with their API quotas, so that's something to keep in mind.

If you want to implement this for me to review and consider adding to the production version, feel free to fork the project and add the necessary changes. 🙂
