### ISSUE TITLE
Add option to remove "accidental" stop/starts from activity

### ISSUE THREAD

**Issue by sticilface** [strautomator/core#49]
Love the work btw,  thank you.  

Strava annoyingly does not allow you to alter the following behaviour.  
It gives you moving time for an activity if it is continuous, however, if you have a single stop/start during the activity then it gives you the overall time for the activity.  I normally don't start/stop the timer during an activity... however, sometimes it gets caught on jacket or something... and occurs accidentally.  

Strava then reports the overall moving time = activity time...  

Can Strautomator have an option to clean stop/starts from an activity so strava calculates moving time correctly?

**Comment by igoramadas** [comment]
Unfortunately there's no way to edit the activity file once it's been uploaded to Strava, so it's not possible to change the moving time / starts / stops. That's a limitation on the Strava API, otherwise I would definitely implement it as I have a similar use case myself (watch button being pressed if I bent my wrist).

Sorry :-(

**Comment by sticilface** [comment]
that makes sense!  Thank you anyways
