### ISSUE TITLE
Feature request: mid-ride location and weather tags

### ISSUE THREAD

**Issue by dintort** [strautomator/core#50]
Currently, only start and end location tags are supported, but 99% of my rides start and end at the same place - home, so I have no use for them.
It would be awesome to add location tags for a point half-way through the ride (cityMiddle/countryMiddle) - which is roughly the destination of the ride - to be able to e.g. append it to the ride name.
Currently, I have to do it manually for each ride.

Less important, but also weather tags for the mid-point location could arguably be more useful than beginning/end.

Thank you.

**Comment by igoramadas** [comment]
Hi @dintort , the weather and city for the mid point of the ride is already implement but available to PRO users only, due to the extra API calls required.

In case you have a PRO subscription, the base ${weather.xxx} tags will point to the weather at the middle of the activity. You can still use ${weather.start.xxx} and ${weather.end.xxx} to get data for the start and end.

And you can use the cityMid tag to get the city at the mid point.

**Comment by dintort** [comment]
Hi @igoramadas, 

Thanks a lot for your reply!
I actually found the cityMid tag by searching through the code yesterday right after posting this issue.
I tried using it but it does not work for some reason. I do have the PRO subscription.
By your suggestion, I also tried the mid-point weather, and it works just fine, thanks!

Here is my test automation:
`"value": "cityStart=${cityStart}, cityEnd=${cityEnd}, cityMid=${cityMid}, weather.start.summary=${weather.start.summary}, weather.summary=${weather.summary}, "`

but all I get is:
` cityStart=Copenhagen, cityEnd=Farum, cityMid=, weather.start.summary=Warm, mostly clear, weather.summary=Warm, clear,`

debugging activity shows that the mid location is detected correctly:
`locationMid - 55.70189, 12.46391`

Also, neither cityMid nor weather.xxx tags are shown as available in the UI, so there is no way to know about them without digging through the code.
